import { MySQLDatabase } from "@/infrastructure/database/MySQLDatabase";
import ChallengeCommentsRepository from "@/infrastructure/database/repositories/ChallengeCommentsRepository";
import ChallengesRepository from "@/infrastructure/database/repositories/ChallengesRepository";
import CommentLikesRepository from "@/infrastructure/database/repositories/CommentLikesRepository";
import EventChallengesRepository from "@/infrastructure/database/repositories/EventChallengesRepository";
import EventParticipantsRepository from "@/infrastructure/database/repositories/EventParticipantsRepository";
import EventsRepository from "@/infrastructure/database/repositories/EventsRepository";
import JobApplicationsRepository from "@/infrastructure/database/repositories/JobApplicationsRepository";
import JobPostsRepository from "@/infrastructure/database/repositories/JobPostsRepository";
import MembersRepository from "@/infrastructure/database/repositories/MembersRepository";
import OrganizationChallengesRepository from "@/infrastructure/database/repositories/OrganizationChallengesRepository";
import OrganizationsRepository from "@/infrastructure/database/repositories/OrganizationsRepository";
import PermissionsRepository from "@/infrastructure/database/repositories/PermissionsRepository";
import SkillsRepository from "@/infrastructure/database/repositories/SkillsRepository";
import SubmissionsRepository from "@/infrastructure/database/repositories/SubmissionsRepository";
import TeamMembersRepository from "@/infrastructure/database/repositories/TeamMembersRepository";
import TeamsRepository from "@/infrastructure/database/repositories/TeamsRepository";
import TestCaseInputsRepository from "@/infrastructure/database/repositories/TestCaseInputsRepository";
import TestCasesRepository from "@/infrastructure/database/repositories/TestCasesRepository";
import UserSessionsRepository from "@/infrastructure/database/repositories/UserSessionsRepository";
import UsersRepository from "@/infrastructure/database/repositories/UsersRepository";

export const database = new MySQLDatabase();

export const usersRepository = new UsersRepository(database);
export const userSessionsRepository = new UserSessionsRepository(database);
export const challengesRepository = new ChallengesRepository(database);
export const organizationsRepository = new OrganizationsRepository(database);
export const jobPostsRepository = new JobPostsRepository(database);
export const jobApplicationsRepository = new JobApplicationsRepository(database);
export const eventsRepository = new EventsRepository(database);
export const membersRepository = new MembersRepository(database);
export const permissionsRepository = new PermissionsRepository(database);
export const eventParticipantsRepository = new EventParticipantsRepository(database);
export const eventChallengesRepository = new EventChallengesRepository(database);
export const teamsRepository = new TeamsRepository(database);
export const teamMembersRepository = new TeamMembersRepository(database);
export const challengeCommentsRepository = new ChallengeCommentsRepository(database);
export const commentLikesRepository = new CommentLikesRepository(database);
export const testCasesRepository = new TestCasesRepository(database);
export const testCaseInputsRepository = new TestCaseInputsRepository(database);
export const submissionsRepository = new SubmissionsRepository(database);
export const organizationChallengesRepository = new OrganizationChallengesRepository(database);
export const skillsRepository = new SkillsRepository(database);